module Files (
  getDataFileName )
  where

import           ClassyPrelude hiding (getLine, putStrLn, on)
import           Filesystem (isFile)
import qualified Paths_Jane

-- | Returns path to a data file. First it looks in the current folder, and
-- then calls @getDataFileName@ from autogenerated @Paths_Jane@ module if the
-- file isn't found.
getDataFileName :: FilePath -> IO FilePath
getDataFileName f = do
  exists <- isFile f
  if exists
    then return f
    else fpFromString <$> Paths_Jane.getDataFileName (fpToString f)
